  camera_manager.cpp
  camera_s.cpp
  object_manager.cpp
  object_rotate.cpp
  player.cpp
  material_for_collider.cpp
  gameobject.cpp
  gameobject_manager.cpp
  ALP_broadphase.cpp
  ALP_collider.cpp
  ALP_generate_contact.cpp
  ALP_integrate.cpp
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(91,55): error C2039: 'vertices': 'Adollib::physics_function::Meshcoll_data' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP__meshcoll_data.h(43): message : 'Adollib::physics_function::Meshcoll_data' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(91,2): error C2530: 'vertex': 参照が初期化されずに宣言されています。
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(91,29): error C2143: 構文エラー: ';' が ':' の前にありません。
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(91,63): error C2143: 構文エラー: ';' が ')' の前にありません。
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(232,44): error C2039: 'facet_num': 'Adollib::physics_function::Meshcoll_data' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP__meshcoll_data.h(43): message : 'Adollib::physics_function::Meshcoll_data' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(233,44): error C2039: 'facets': 'Adollib::physics_function::Meshcoll_data' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP__meshcoll_data.h(43): message : 'Adollib::physics_function::Meshcoll_data' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(233,22): error C2530: 'facet': 参照が初期化されずに宣言されています。
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(273,45): error C2039: 'facet_num': 'Adollib::physics_function::Meshcoll_data' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP__meshcoll_data.h(43): message : 'Adollib::physics_function::Meshcoll_data' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(274,45): error C2039: 'facets': 'Adollib::physics_function::Meshcoll_data' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP__meshcoll_data.h(43): message : 'Adollib::physics_function::Meshcoll_data' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(274,23): error C2530: 'facet': 参照が初期化されずに宣言されています。
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(327,46): error C2039: 'edge_num': 'Adollib::physics_function::Meshcoll_data' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP__meshcoll_data.h(43): message : 'Adollib::physics_function::Meshcoll_data' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(328,43): error C2039: 'edges': 'Adollib::physics_function::Meshcoll_data' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP__meshcoll_data.h(43): message : 'Adollib::physics_function::Meshcoll_data' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(328,21): error C2530: 'edgeA': 参照が初期化されずに宣言されています。
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(331,49): error C2039: 'vertices': 'Adollib::physics_function::Meshcoll_data' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP__meshcoll_data.h(43): message : 'Adollib::physics_function::Meshcoll_data' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(331,103): error C2039: 'vertices': 'Adollib::physics_function::Meshcoll_data' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP__meshcoll_data.h(43): message : 'Adollib::physics_function::Meshcoll_data' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(331,27): error C2530: 'edgeVecA': 参照が初期化されずに宣言されています。
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(332,48): error C2039: 'edge_num': 'Adollib::physics_function::Meshcoll_data' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP__meshcoll_data.h(43): message : 'Adollib::physics_function::Meshcoll_data' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(333,45): error C2039: 'edges': 'Adollib::physics_function::Meshcoll_data' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP__meshcoll_data.h(43): message : 'Adollib::physics_function::Meshcoll_data' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(333,23): error C2530: 'edgeB': 参照が初期化されずに宣言されています。
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(336,69): error C2039: 'vertices': 'Adollib::physics_function::Meshcoll_data' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP__meshcoll_data.h(43): message : 'Adollib::physics_function::Meshcoll_data' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(336,123): error C2039: 'vertices': 'Adollib::physics_function::Meshcoll_data' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP__meshcoll_data.h(43): message : 'Adollib::physics_function::Meshcoll_data' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(357,69): error C2039: 'vertices': 'Adollib::physics_function::Meshcoll_data' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP__meshcoll_data.h(43): message : 'Adollib::physics_function::Meshcoll_data' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(357,100): error C2660: 'Adollib::vector3_dot': 関数に 1 個の引数を指定できません。
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Math\vector_e.h(191,23): message : 'Adollib::vector3_dot' の宣言を確認してください (ソース ファイルをコンパイルしています Scripts\Physics\ALP_generate_contact.cpp)
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(357,145): error C2039: 'vertices': 'Adollib::physics_function::Meshcoll_data' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP__meshcoll_data.h(43): message : 'Adollib::physics_function::Meshcoll_data' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(357,176): error C2660: 'Adollib::vector3_dot': 関数に 1 個の引数を指定できません。
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Math\vector_e.h(191,23): message : 'Adollib::vector3_dot' の宣言を確認してください (ソース ファイルをコンパイルしています Scripts\Physics\ALP_generate_contact.cpp)
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(445,44): error C2039: 'facet_num': 'Adollib::physics_function::Meshcoll_data' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP__meshcoll_data.h(43): message : 'Adollib::physics_function::Meshcoll_data' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(446,44): error C2039: 'facets': 'Adollib::physics_function::Meshcoll_data' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP__meshcoll_data.h(43): message : 'Adollib::physics_function::Meshcoll_data' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(446,23): error C2530: 'facet': 参照が初期化されずに宣言されています。
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(739,25): error C2039: 'is_Convex': 'Adollib::physics_function::Meshcoll_data' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP__meshcoll_data.h(43): message : 'Adollib::physics_function::Meshcoll_data' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(753,44): error C2039: 'facet_num': 'Adollib::physics_function::Meshcoll_data' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP__meshcoll_data.h(43): message : 'Adollib::physics_function::Meshcoll_data' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(754,44): error C2039: 'facets': 'Adollib::physics_function::Meshcoll_data' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP__meshcoll_data.h(43): message : 'Adollib::physics_function::Meshcoll_data' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(754,23): error C2530: 'nor': 参照が初期化されずに宣言されています。
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(755,44): error C2039: 'vertices': 'Adollib::physics_function::Meshcoll_data' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP__meshcoll_data.h(43): message : 'Adollib::physics_function::Meshcoll_data' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(755,76): error C2039: 'facets': 'Adollib::physics_function::Meshcoll_data' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP__meshcoll_data.h(43): message : 'Adollib::physics_function::Meshcoll_data' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(755,23): error C2530: 'pos': 参照が初期化されずに宣言されています。
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(1086,23): error C2039: 'is_Convex': 'Adollib::physics_function::Meshcoll_data' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP__meshcoll_data.h(43): message : 'Adollib::physics_function::Meshcoll_data' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(1086,61): error C2039: 'is_Convex': 'Adollib::physics_function::Meshcoll_data' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP__meshcoll_data.h(43): message : 'Adollib::physics_function::Meshcoll_data' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(1106,57): error C2039: 'facets': 'Adollib::physics_function::Meshcoll_data' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP__meshcoll_data.h(43): message : 'Adollib::physics_function::Meshcoll_data' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(1106,30): error C2530: 'nerest_facet': 参照が初期化されずに宣言されています。
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(1122,61): error C2039: 'vertex_num': 'Adollib::physics_function::Meshcoll_data' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP__meshcoll_data.h(43): message : 'Adollib::physics_function::Meshcoll_data' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(1124,48): error C2039: 'vertices': 'Adollib::physics_function::Meshcoll_data' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP__meshcoll_data.h(43): message : 'Adollib::physics_function::Meshcoll_data' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(1125,55): error C2039: 'vertices': 'Adollib::physics_function::Meshcoll_data' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP__meshcoll_data.h(43): message : 'Adollib::physics_function::Meshcoll_data' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(1130,35): error C2039: 'vertices': 'Adollib::physics_function::Meshcoll_data' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP__meshcoll_data.h(43): message : 'Adollib::physics_function::Meshcoll_data' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(1143,60): error C2039: 'facet_num': 'Adollib::physics_function::Meshcoll_data' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP__meshcoll_data.h(43): message : 'Adollib::physics_function::Meshcoll_data' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(1145,47): error C2039: 'facets': 'Adollib::physics_function::Meshcoll_data' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP__meshcoll_data.h(43): message : 'Adollib::physics_function::Meshcoll_data' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(1149,32): error C2039: 'vertices': 'Adollib::physics_function::Meshcoll_data' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP__meshcoll_data.h(43): message : 'Adollib::physics_function::Meshcoll_data' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(1149,70): error C2039: 'facets': 'Adollib::physics_function::Meshcoll_data' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP__meshcoll_data.h(43): message : 'Adollib::physics_function::Meshcoll_data' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(1150,32): error C2039: 'vertices': 'Adollib::physics_function::Meshcoll_data' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP__meshcoll_data.h(43): message : 'Adollib::physics_function::Meshcoll_data' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(1150,70): error C2039: 'facets': 'Adollib::physics_function::Meshcoll_data' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP__meshcoll_data.h(43): message : 'Adollib::physics_function::Meshcoll_data' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(1151,32): error C2039: 'vertices': 'Adollib::physics_function::Meshcoll_data' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP__meshcoll_data.h(43): message : 'Adollib::physics_function::Meshcoll_data' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(1151,70): error C2039: 'facets': 'Adollib::physics_function::Meshcoll_data' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP__meshcoll_data.h(43): message : 'Adollib::physics_function::Meshcoll_data' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(1152,32): error C2039: 'facets': 'Adollib::physics_function::Meshcoll_data' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP__meshcoll_data.h(43): message : 'Adollib::physics_function::Meshcoll_data' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(1148,6): error C2660: 'Adollib::Closest_func::get_closestP_point_triangle': 関数に 2 個の引数を指定できません。
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Math\closest_func.h(60,8): message : 'Adollib::Closest_func::get_closestP_point_triangle' の宣言を確認してください (ソース ファイルをコンパイルしています Scripts\Physics\ALP_generate_contact.cpp)
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(1185,57): error C2039: 'facets': 'Adollib::physics_function::Meshcoll_data' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP__meshcoll_data.h(43): message : 'Adollib::physics_function::Meshcoll_data' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(1185,30): error C2530: 'nerest_facet': 参照が初期化されずに宣言されています。
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(1201,61): error C2039: 'vertex_num': 'Adollib::physics_function::Meshcoll_data' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP__meshcoll_data.h(43): message : 'Adollib::physics_function::Meshcoll_data' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(1203,48): error C2039: 'vertices': 'Adollib::physics_function::Meshcoll_data' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP__meshcoll_data.h(43): message : 'Adollib::physics_function::Meshcoll_data' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(1204,55): error C2039: 'vertices': 'Adollib::physics_function::Meshcoll_data' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP__meshcoll_data.h(43): message : 'Adollib::physics_function::Meshcoll_data' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(1209,35): error C2039: 'vertices': 'Adollib::physics_function::Meshcoll_data' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP__meshcoll_data.h(43): message : 'Adollib::physics_function::Meshcoll_data' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(1222,60): error C2039: 'facet_num': 'Adollib::physics_function::Meshcoll_data' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP__meshcoll_data.h(43): message : 'Adollib::physics_function::Meshcoll_data' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(1224,47): error C2039: 'facets': 'Adollib::physics_function::Meshcoll_data' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP__meshcoll_data.h(43): message : 'Adollib::physics_function::Meshcoll_data' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(1228,32): error C2039: 'vertices': 'Adollib::physics_function::Meshcoll_data' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP__meshcoll_data.h(43): message : 'Adollib::physics_function::Meshcoll_data' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(1228,70): error C2039: 'facets': 'Adollib::physics_function::Meshcoll_data' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP__meshcoll_data.h(43): message : 'Adollib::physics_function::Meshcoll_data' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(1229,32): error C2039: 'vertices': 'Adollib::physics_function::Meshcoll_data' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP__meshcoll_data.h(43): message : 'Adollib::physics_function::Meshcoll_data' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(1229,70): error C2039: 'facets': 'Adollib::physics_function::Meshcoll_data' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP__meshcoll_data.h(43): message : 'Adollib::physics_function::Meshcoll_data' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(1230,32): error C2039: 'vertices': 'Adollib::physics_function::Meshcoll_data' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP__meshcoll_data.h(43): message : 'Adollib::physics_function::Meshcoll_data' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(1230,70): error C2039: 'facets': 'Adollib::physics_function::Meshcoll_data' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP__meshcoll_data.h(43): message : 'Adollib::physics_function::Meshcoll_data' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(1231,32): error C2039: 'facets': 'Adollib::physics_function::Meshcoll_data' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP__meshcoll_data.h(43): message : 'Adollib::physics_function::Meshcoll_data' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(1227,6): error C2660: 'Adollib::Closest_func::get_closestP_point_triangle': 関数に 2 個の引数を指定できません。
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Math\closest_func.h(60,8): message : 'Adollib::Closest_func::get_closestP_point_triangle' の宣言を確認してください (ソース ファイルをコンパイルしています Scripts\Physics\ALP_generate_contact.cpp)
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(1261,41): error C2039: 'edges': 'Adollib::physics_function::Meshcoll_data' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP__meshcoll_data.h(43): message : 'Adollib::physics_function::Meshcoll_data' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(1261,22): error C2530: 'edgeA': 参照が初期化されずに宣言されています。
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(1262,41): error C2039: 'edges': 'Adollib::physics_function::Meshcoll_data' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP__meshcoll_data.h(43): message : 'Adollib::physics_function::Meshcoll_data' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(1262,22): error C2530: 'edgeB': 参照が初期化されずに宣言されています。
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(1265,23): error C2039: 'vertices': 'Adollib::physics_function::Meshcoll_data' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP__meshcoll_data.h(43): message : 'Adollib::physics_function::Meshcoll_data' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(1266,23): error C2039: 'vertices': 'Adollib::physics_function::Meshcoll_data' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP__meshcoll_data.h(43): message : 'Adollib::physics_function::Meshcoll_data' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(1269,23): error C2039: 'vertices': 'Adollib::physics_function::Meshcoll_data' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP__meshcoll_data.h(43): message : 'Adollib::physics_function::Meshcoll_data' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_generate_contact.cpp(1270,23): error C2039: 'vertices': 'Adollib::physics_function::Meshcoll_data' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP__meshcoll_data.h(43): message : 'Adollib::physics_function::Meshcoll_data' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_broadphase.cpp(47,30): error C2039: 'dop14': 'Adollib::physics_function::ALP_Collider' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_collider.h(29): message : 'Adollib::physics_function::ALP_Collider' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_broadphase.cpp(47,60): error C2039: 'dop14': 'Adollib::physics_function::ALP_Collider' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_collider.h(29): message : 'Adollib::physics_function::ALP_Collider' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_broadphase.cpp(53,30): error C2039: 'dop14': 'Adollib::physics_function::ALP_Collider' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_collider.h(29): message : 'Adollib::physics_function::ALP_Collider' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_broadphase.cpp(53,60): error C2039: 'dop14': 'Adollib::physics_function::ALP_Collider' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_collider.h(29): message : 'Adollib::physics_function::ALP_Collider' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_broadphase.cpp(71,29): error C2039: 'dop14': 'Adollib::physics_function::ALP_Collider' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_collider.h(29): message : 'Adollib::physics_function::ALP_Collider' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_broadphase.cpp(71,62): error C2039: 'dop14': 'Adollib::physics_function::ALP_Collider' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_collider.h(29): message : 'Adollib::physics_function::ALP_Collider' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_broadphase.cpp(74,29): error C2039: 'dop14': 'Adollib::physics_function::ALP_Collider' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_collider.h(29): message : 'Adollib::physics_function::ALP_Collider' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_broadphase.cpp(74,62): error C2039: 'dop14': 'Adollib::physics_function::ALP_Collider' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_collider.h(29): message : 'Adollib::physics_function::ALP_Collider' の宣言を確認してください
  ALP_midphase.cpp
  ALP_physics.cpp
  ALP_resolve_contact.cpp
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_collider.cpp(84,2): error C2065: 'dop14': 定義されていない識別子です。
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_collider.cpp(86,3): error C2065: 'dop14': 定義されていない識別子です。
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_collider.cpp(87,3): error C2065: 'dop14': 定義されていない識別子です。
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_collider.cpp(92,2): error C2065: 'dop14': 定義されていない識別子です。
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_collider.cpp(118,5): error C2065: 'dop14': 定義されていない識別子です。
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_collider.cpp(119,5): error C2065: 'dop14': 定義されていない識別子です。
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_collider.cpp(128,2): error C2065: 'dop14': 定義されていない識別子です。
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_collider.cpp(130,3): error C2065: 'dop14': 定義されていない識別子です。
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_collider.cpp(135,2): error C2065: 'dop14': 定義されていない識別子です。
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_collider.cpp(140,3): error C2065: 'dop14': 定義されていない識別子です。
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_collider.cpp(141,3): error C2065: 'dop14': 定義されていない識別子です。
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_collider.cpp(147,15): error C2065: 'dopbase': 定義されていない識別子です。
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_collider.cpp(149,15): error C2065: 'dopbase': 定義されていない識別子です。
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_collider.cpp(157,8): error C2065: 'dop14': 定義されていない識別子です。
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_collider.cpp(157,28): error C2065: 'dop14': 定義されていない識別子です。
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_collider.cpp(158,8): error C2065: 'dop14': 定義されていない識別子です。
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_collider.cpp(158,28): error C2065: 'dop14': 定義されていない識別子です。
  ALP__physics_manager.cpp
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Mesh\material_for_collider.cpp(59,50): warning C4305: '引数': 'double' から 'float' へ切り詰めます。
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_midphase.cpp(17,23): error C2039: 'dop14': 'Adollib::physics_function::ALP_Collider' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_collider.h(29): message : 'Adollib::physics_function::ALP_Collider' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_midphase.cpp(17,42): error C2039: 'dop14': 'Adollib::physics_function::ALP_Collider' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_collider.h(29): message : 'Adollib::physics_function::ALP_Collider' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_midphase.cpp(21,40): error C2039: 'dop14': 'Adollib::physics_function::ALP_Collider' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_collider.h(29): message : 'Adollib::physics_function::ALP_Collider' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_midphase.cpp(21,59): error C2039: 'dop14': 'Adollib::physics_function::ALP_Collider' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_collider.h(29): message : 'Adollib::physics_function::ALP_Collider' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_midphase.cpp(21,1): error C2660: 'Adollib::vector3_dot': 関数に 1 個の引数を指定できません。
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Math\vector_e.h(191,23): message : 'Adollib::vector3_dot' の宣言を確認してください (ソース ファイルをコンパイルしています Scripts\Physics\ALP_midphase.cpp)
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_midphase.cpp(21,79): error C2039: 'dop14': 'Adollib::physics_function::ALP_Collider' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_collider.h(29): message : 'Adollib::physics_function::ALP_Collider' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_midphase.cpp(21,101): error C2039: 'dop14': 'Adollib::physics_function::ALP_Collider' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_collider.h(29): message : 'Adollib::physics_function::ALP_Collider' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_midphase.cpp(22,40): error C2039: 'dop14': 'Adollib::physics_function::ALP_Collider' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_collider.h(29): message : 'Adollib::physics_function::ALP_Collider' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_midphase.cpp(22,59): error C2039: 'dop14': 'Adollib::physics_function::ALP_Collider' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_collider.h(29): message : 'Adollib::physics_function::ALP_Collider' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_midphase.cpp(22,1): error C2660: 'Adollib::vector3_dot': 関数に 1 個の引数を指定できません。
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Math\vector_e.h(191,23): message : 'Adollib::vector3_dot' の宣言を確認してください (ソース ファイルをコンパイルしています Scripts\Physics\ALP_midphase.cpp)
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_midphase.cpp(22,79): error C2039: 'dop14': 'Adollib::physics_function::ALP_Collider' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_collider.h(29): message : 'Adollib::physics_function::ALP_Collider' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_midphase.cpp(22,101): error C2039: 'dop14': 'Adollib::physics_function::ALP_Collider' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_collider.h(29): message : 'Adollib::physics_function::ALP_Collider' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_midphase.cpp(24,51): error C2039: 'dop14': 'Adollib::physics_function::ALP_Collider' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_collider.h(29): message : 'Adollib::physics_function::ALP_Collider' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_midphase.cpp(24,70): error C2039: 'dop14': 'Adollib::physics_function::ALP_Collider' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_collider.h(29): message : 'Adollib::physics_function::ALP_Collider' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_midphase.cpp(24,79): error C2660: 'Adollib::vector3_dot': 関数に 1 個の引数を指定できません。
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Math\vector_e.h(191,23): message : 'Adollib::vector3_dot' の宣言を確認してください (ソース ファイルをコンパイルしています Scripts\Physics\ALP_midphase.cpp)
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_midphase.cpp(25,22): error C2039: 'dop14': 'Adollib::physics_function::ALP_Collider' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_collider.h(29): message : 'Adollib::physics_function::ALP_Collider' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_midphase.cpp(25,44): error C2039: 'dop14': 'Adollib::physics_function::ALP_Collider' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_collider.h(29): message : 'Adollib::physics_function::ALP_Collider' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_midphase.cpp(26,51): error C2039: 'dop14': 'Adollib::physics_function::ALP_Collider' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_collider.h(29): message : 'Adollib::physics_function::ALP_Collider' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_midphase.cpp(26,70): error C2039: 'dop14': 'Adollib::physics_function::ALP_Collider' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_collider.h(29): message : 'Adollib::physics_function::ALP_Collider' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_midphase.cpp(26,79): error C2660: 'Adollib::vector3_dot': 関数に 1 個の引数を指定できません。
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Math\vector_e.h(191,23): message : 'Adollib::vector3_dot' の宣言を確認してください (ソース ファイルをコンパイルしています Scripts\Physics\ALP_midphase.cpp)
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_midphase.cpp(27,22): error C2039: 'dop14': 'Adollib::physics_function::ALP_Collider' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_collider.h(29): message : 'Adollib::physics_function::ALP_Collider' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_midphase.cpp(27,44): error C2039: 'dop14': 'Adollib::physics_function::ALP_Collider' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_collider.h(29): message : 'Adollib::physics_function::ALP_Collider' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_midphase.cpp(44,81): error C2039: 'dop14': 'Adollib::physics_function::ALP_Collider' のメンバーではありません
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_collider.h(29): message : 'Adollib::physics_function::ALP_Collider' の宣言を確認してください
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Physics\ALP_midphase.cpp(44,93): error C2660: 'Adollib::vector3_dot': 関数に 1 個の引数を指定できません。
C:\Users\waaaa\Documents\Adollib\Adollib\Adollib\Scripts\Math\vector_e.h(191,23): message : 'Adollib::vector3_dot' の宣言を確認してください (ソース ファイルをコンパイルしています Scripts\Physics\ALP_midphase.cpp)
  collider__base.cpp
  contact.cpp
  scene_game.cpp
